---
- name: Configuration commune à toutes les machines
  hosts: all
  become: true
  roles:
    - common

- name: Machine d'administration
  hosts: admin
  become: true
  roles:
    - admin
    - role: wireguard
      tags: [wireguard]

- name: Gestion des administrateurs
  import_playbook: admins.yml
