---
# Accès à l'API de l'hyperviseur
pve_api_host: 10.99.0.100
pve_api_user: ansible@pve
pve_api_token_id: smb111
pve_api_token_secret: "{{ vault_pve_token }}"
pve_node: pve                 # nom du nœud, tel qu'il apparaît dans l'interface
pve_storage: local-lvm
pve_template: debian-13-template

# Réseaux
pve_bridge_interne: vmbr1
pve_bridge_externe: vmbr0
reseau_interne: 10.10.0
passerelle_interne: 10.10.0.1
fw_ip_externe: 192.168.1.70
passerelle_externe: 192.168.1.254
